### ISSUE TITLE
Избавиться от кастов и получить длинну простым способом. 

### ISSUE THREAD

**Issue by Shidlowski** [PavloKirif/exercise_1.2#3]
https://github.com/PavloKirif/exercise_1.2/blob/e5e7fd176182bf13cd97c45d9a8b7922526c2dcb/teacher/teacher.cpp#L33
Попробуй использовать std::map вместо двух массивов и станет все проще

**Comment by PavloKirif** [comment]
Исправлено

**Comment by Shidlowski** [comment]
Все как и было раньше, нет исправлений.
