### ISSUE TITLE
Избавиться от хардкод путей в классе.

### ISSUE THREAD

**Issue by Shidlowski** [PavloKirif/exercise_1.2#4]
https://github.com/PavloKirif/exercise_1.2/blob/e5e7fd176182bf13cd97c45d9a8b7922526c2dcb/teacher/teacher.cpp#L54
Лучше передать аргументом путь куда сохранять. Не следуется прописывать такие пути в описаниях класса и т.д

**Comment by PavloKirif** [comment]
Исправлено

**Comment by Shidlowski** [comment]
Нет исправлений.
